---
# Copyright (c) Ansible Project
# Adapted by SirUli for FroniusSmartmeter
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

name: Bug report
description: Create a report to help us improve

body:
- type: markdown
  attributes:
    value: |
      ⚠
      Verify first that your issue is not [already reported on GitHub][issue search].
      Also test if the latest release is affected too.
      *Complete **all** sections as described, this form is processed automatically.*

      [issue search]: https://github.com/SirUli/FroniusSmartmeter/search?q=is%3Aissue&type=issues


- type: textarea
  attributes:
    label: Summary
    description: Explain the problem briefly below.
    placeholder: >-
      When I try to do X with the script from the main branch on GitHub, Y
      breaks in a way Z under the env E. Here are all the details I know
      about this problem...
  validations:
    required: true

- type: dropdown
  attributes:
    label: Issue Type
    # FIXME: Once GitHub allows defining the default choice, update this
    options:
    - Bug Report
  validations:
    required: true

- type: textarea
  attributes:
    label: FroniusSmartmeter Version
    description: >-
      Paste the displayed version from the SetupHelper between
      triple backticks.
    value: |
      ```console (paste below)
      
      ```
  validations:
    required: true

- type: textarea
  attributes:
    label: Steps to Reproduce
    description: |
      Describe exactly how to reproduce the problem.

      **HINT:** You can paste https://gist.github.com links for larger files.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected Results
    description: >-
      Describe what you expected to happen when running the steps above.
    placeholder: >-
      I expected X to happen because I assumed Y.
      that it did not.
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Results
    description: |
      Describe what actually happened.
...
